# -*- coding: utf-8 -*-
"""VADER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/XGHouFTW/ISEF-2022/blob/main/VADER.ipynb
"""

# need to pip install vaderSentiment
import sys
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

script, filepath, column_name = sys.argv

def main(path, data, text_column_name):
  # Take in a pd.DataFrame, and create a new column corresponding to the sentiment scores of each comment
  # resulting data will be written to <path>.csv

  sid_obj = SentimentIntensityAnalyzer()
  scores=pd.DataFrame(data[text_column_name].apply(lambda x: VADER(str(x), sid_obj)))
  data["scores"] = scores["body"]
  data.to_csv(path)

  return None

def VADER(sentence, sid) -> dict:
    return tuple(sid.polarity_scores(sentence).values())

if __name__ == "__main__":
  # TODO
  df = pd.read_csv(filepath)
  main(filepath, df, column_name)
